### ISSUE TITLE
index.html not optimized for non-root installs

### ISSUE THREAD

**Issue by Calebrw** [4cm4k1/autopool.io#4]
Index.html currently references assess and local links in such a way to always refer to the base directory of a given domain and cannot be installed in an environment where /public/ is above the base directory.

For instance "http://autopool.io/public/index.html" should refer to "http://autopool.io/public/assets/a_file.js" but actually refers to "http://autopool.io/assets/a_file.js" which results in a 404 Not Found Error.

Properly setting up this type of flexible base directory would require a configuration file of some type.

Be sure to include that file in .gitignore and only upload a base/same file that end users can use to configure the application before they start running it on their end.

**Comment by 4cm4k1** [comment]
This repo assumes that you are running a Node.js server to run the application. After cloning the repo, running `npm install` and then `npm start` will get you up and running. The README will be updated accordingly when this project reaches production release status.

**Comment by Calebrw** [comment]
Thanks for the update, I had the wrong server port for my local install and that caused this error.
